[entity.A]
# primary entity
primary = true
# literal type
# internally stored as a singleton tuple struct (e.g. `pub struct A(pub String);`)
type = "String"
dimensions = ["i"]

# [beta]_i : A -> [B]_j
[entity.B]
# tuple type: (literal [, ...])
# internally stored as a tuple struct (e.g. `pub struct B(pub A, pub usize);`)
type = "(A, usize)"
dimensions = ["i", "j"]
definition = "beta|i"
from = ["A"]
pool = 8

# [gamma]_i : A -> [C]_k
[entity.C]
type = "usize"
dimensions = ["i", "k"]
definition = "gamma|i"
from = ["A"]
pool = 8

# [delta]_i,j,k : A, B, C -> D
[entity.D]
# struct type: {name(literal) [, ...]}
type = "{a(A), b(B), c(C)}"
dimensions = ["i", "j", "k"]
definition = "delta|i,j,k"
from = ["A", "B", "C"]
pool = 4

# [epsilon]_i,k : [B]_j, [D]_j -> E
[entity.E]
type = "{b(Vec<B>), d(Vec<D>)}"
dimensions = ["i", "k"]
definition = "epsilon|i,k"
from = ["B|j", "D|j"]
pool = 4

# [zeta]_i : [C]_k, [E]_k -> F
[entity.F]
# enum type: (Variant{name(literal) [, ...]} | Variant(literal [, ...]) | Variant [+ ...])
type = "(Success{c(Vec<C>), e(Vec<E>)} + Failure(String, Option<C>, Option<E>))"
dimensions = ["i"]
definition = "zeta|i"
from = ["C|k", "E|k"]
