[workspace]
members = ["operon", "operon-macros"]
exclude = ["examples"]
resolver = "2"

[workspace.package]
version = "0.2.3"
edition = "2024"
rust-version = "1.91"
publish = ["kellnr"]
authors = [
    "Sungbin Moon <sb.moon@asteromorph.com>",
    "Jiho Park <jh.park@asteromorph.com>",
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Asteromorph-Corp/operon"
readme = "README.md"

[workspace.dependencies]
operon-macros = { version = "0.2.3", registry = "kellnr", path = "operon-macros" }
