[workspace]
members = ["operon", "operon-macros", "tests/*"]
default-members = ["operon", "operon-macros"]
resolver = "2"

[workspace.package]
version = "0.7.0"
edition = "2024"
rust-version = "1.91"
authors = [
    "Sungbin Moon <sb.moon@asteromorph.com>",
    "Jiho Park <jh.park@asteromorph.com>",
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Asteromorph-Corp/operon"
readme = "README.md"
homepage = "https://asteromorph.com/"

[workspace.dependencies]
operon-macros = { version = "0.7.0", path = "operon-macros" }
