[package]
name = "operon"
version = "0.1.0"
authors = [
    "Sungbin Moon <sb.moon@asteromorph.com>",
    "Jiho Park <jh.park@asteromorph.com>",
]
description = "A workflow engine for parallel, incremental scheduling of DAG-defined multiplex tasks."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Asteromorph-Corp/operon"
readme = "../README.md"
edition = "2024"
rust-version = "1.88"

[dependencies]
async-trait = "0.1.88"
bytes = "1.10.1"
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
csv = "1.3.1"
deadpool-postgres = "0.14.1"
futures = "0.3.31"
indexmap = "2.9.0"
log = { version = "0.4.27", features = ["std"] }
operon-macros = { path = "../macros" }
postgres-types = { version = "0.2.9", features = ["derive"] }
ratatui = "0.29.0"
secrecy = "0.10.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
textwrap = "0.16.2"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
tokio-postgres = { version = "0.7.13", features = ["with-serde_json-1"] }

[dev-dependencies]
indoc = "2.0.7"
rstest = "0.26.1"
